// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bexdvmnrwqlcfxygpnlu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJleGR2bW5yd3FsY2Z4eWdwbmx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMjc3NzgsImV4cCI6MjA2NjYwMzc3OH0.M-rmoA2KwV9uFhl8a1PYVMqMMDaXEgmq0BqaGqcJ_C4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);